# Generated by Django 3.1.2 on 2020-10-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'additive',
            },
        ),
        migrations.CreateModel(
            name='Fragrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'fragrance',
            },
        ),
        migrations.CreateModel(
            name='Lipid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('lauric', models.IntegerField()),
                ('myristic', models.IntegerField()),
                ('palmitic', models.IntegerField()),
                ('stearic', models.IntegerField()),
                ('ricinoleic', models.IntegerField()),
                ('oleic', models.IntegerField()),
                ('linoleic', models.IntegerField()),
                ('linolenic', models.IntegerField()),
                ('hardness', models.IntegerField()),
                ('cleansing', models.IntegerField()),
                ('conditioning', models.IntegerField()),
                ('bubbly', models.IntegerField()),
                ('creamy', models.IntegerField()),
                ('iodine', models.IntegerField()),
                ('ins', models.IntegerField()),
                ('inci_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lipid',
            },
        ),
        migrations.CreateModel(
            name='Lye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('kind', models.CharField(choices=[('naoh', 'NaOH'), ('koh', 'KOH')], default='naoh', max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'lye',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='RecipeLipid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('percentage', models.FloatField()),
                ('lipid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.lipid')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.recipe')),
            ],
            options={
                'db_table': 'recipe_lipid',
            },
        ),
        migrations.CreateModel(
            name='RecipeFragrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('percentage', models.FloatField()),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.fragrance')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.recipe')),
            ],
            options={
                'db_table': 'recipe_fragrance',
            },
        ),
        migrations.CreateModel(
            name='RecipeBatchLye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('weight', models.FloatField()),
                ('discount', models.FloatField()),
                ('cost', models.FloatField()),
                ('lye', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.lye')),
            ],
            options={
                'db_table': 'recipe_batch_lye',
            },
        ),
        migrations.CreateModel(
            name='RecipeBatchLipid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('weight', models.FloatField()),
                ('cost', models.FloatField()),
                ('lipid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.lipid')),
            ],
            options={
                'db_table': 'recipe_batch_lipid',
            },
        ),
        migrations.CreateModel(
            name='RecipeBatchFragrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('weight', models.FloatField()),
                ('cost', models.FloatField()),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.fragrance')),
            ],
            options={
                'db_table': 'recipe_batch_fragrance',
            },
        ),
        migrations.CreateModel(
            name='RecipeBatchAdditive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('weight', models.FloatField()),
                ('cost', models.FloatField()),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.additive')),
            ],
            options={
                'db_table': 'recipe_batch_additive',
            },
        ),
        migrations.CreateModel(
            name='RecipeBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('batch_id', models.CharField(max_length=16)),
                ('production_date', models.DateTimeField()),
                ('cured_produced', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('lipid_weight', models.FloatField()),
                ('production_weight', models.FloatField()),
                ('cured_weight', models.FloatField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.recipe')),
            ],
            options={
                'db_table': 'recipe_batch',
            },
        ),
        migrations.CreateModel(
            name='RecipeAdditive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('percentage', models.FloatField()),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.additive')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.recipe')),
            ],
            options={
                'db_table': 'recipe_additive',
            },
        ),
        migrations.CreateModel(
            name='LyeInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('purchase_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('weight', models.FloatField()),
                ('concentration', models.FloatField()),
                ('lye', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.lyeinventory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.supplier')),
            ],
            options={
                'db_table': 'lye_inventory',
            },
        ),
        migrations.CreateModel(
            name='LipidInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('purchase_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('weight', models.FloatField()),
                ('sap', models.FloatField()),
                ('naoh', models.FloatField()),
                ('koh', models.FloatField()),
                ('grams_per_liter', models.FloatField()),
                ('lipid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.lipid')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.supplier')),
            ],
            options={
                'db_table': 'lipid_inventory',
            },
        ),
        migrations.CreateModel(
            name='FragranceInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('purchase_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('weight', models.FloatField()),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.fragrance')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.supplier')),
            ],
            options={
                'db_table': 'fragrance_inventory',
            },
        ),
        migrations.CreateModel(
            name='AdditiveInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('purchase_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('weight', models.FloatField()),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.additive')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.supplier')),
            ],
            options={
                'db_table': 'additive_inventory',
            },
        ),
    ]
