# Generated by Django 3.1.2 on 2020-10-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='additive',
            table='additive',
        ),
        migrations.AlterModelTable(
            name='additiveinventory',
            table='additive_inventory',
        ),
        migrations.AlterModelTable(
            name='fragrance',
            table='fragrance',
        ),
        migrations.AlterModelTable(
            name='fragranceinventory',
            table='fragrance_inventory',
        ),
        migrations.AlterModelTable(
            name='lipid',
            table='lipid',
        ),
        migrations.AlterModelTable(
            name='lipidinventory',
            table='lipid_inventory',
        ),
        migrations.AlterModelTable(
            name='lye',
            table='lye',
        ),
        migrations.AlterModelTable(
            name='lyeinventory',
            table='lye_inventory',
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
        migrations.AlterModelTable(
            name='recipeadditive',
            table='recipe_additive',
        ),
        migrations.AlterModelTable(
            name='recipefragrance',
            table='recipe_fragrance',
        ),
        migrations.AlterModelTable(
            name='recipelipid',
            table='recipe_lipid',
        ),
        migrations.AlterModelTable(
            name='recipelye',
            table='recipe_lye',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='supplier',
        ),
    ]
