# Generated by Django 3.1.2 on 2020-10-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipebatch',
            old_name='cured_produced',
            new_name='sellable_date',
        ),
    ]
