# Generated by Django 3.1.2 on 2020-10-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0003_auto_20201010_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipebatch',
            old_name='batch',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='recipebatchadditive',
            name='batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='soap.recipebatch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipebatchfragrance',
            name='batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='soap.recipebatch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipebatchlipid',
            name='batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='soap.recipebatch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipebatchlye',
            name='batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='soap.recipebatch'),
            preserve_default=False,
        ),
    ]
