# Generated by Django 3.1.2 on 2020-10-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0004_auto_20201011_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipid',
            name='family',
            field=models.CharField(choices=[('lauric', 'Lauric Oil'), ('palmitic', 'Palmitic Oil'), ('oleic', 'Oleic Oil'), ('ricinoleic', 'Ricinoleic Oil'), ('linoleic', 'Linoleic Oil'), ('linolenic', 'Linolenic Oil')], default='oleic', max_length=50),
        ),
        migrations.AddField(
            model_name='lipid',
            name='naoh',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
