# Generated by Django 3.1.2 on 2020-10-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0005_auto_20201011_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebatchlye',
            name='lye',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='soap.lye'),
        ),
    ]
