# Generated by Django 3.1.2 on 2020-10-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0006_auto_20201011_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyeinventory',
            name='lye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soap.lye'),
        ),
    ]
