# Generated by Django 3.1.2 on 2020-10-12 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0007_auto_20201012_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeadditive',
            name='additive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='soap.additive'),
        ),
        migrations.AlterField(
            model_name='recipebatchadditive',
            name='additive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='soap.additive'),
        ),
        migrations.AlterField(
            model_name='recipebatchfragrance',
            name='fragrance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='soap.fragrance'),
        ),
        migrations.AlterField(
            model_name='recipebatchlipid',
            name='lipid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='soap.lipid'),
        ),
        migrations.AlterField(
            model_name='recipefragrance',
            name='fragrance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='soap.fragrance'),
        ),
        migrations.AlterField(
            model_name='recipelipid',
            name='lipid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='soap.lipid'),
        ),
    ]
