// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package hello

import (
)


class github.com/sjhitchner/soapcalc/backend/graph/model.Additive(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.Fragrance(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.Inventory(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.Lipid(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.Lye(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.Recipe(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.RecipeAdditive(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.RecipeComposition(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.RecipeFragrance(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.RecipeLipid(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.RecipeLye(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.RecipeQuality(models.Model):
	

class github.com/sjhitchner/soapcalc/backend/graph/model.Supplier(models.Model):
	

class github.com/99designs/gqlgen/graphql/introspection.Directive(models.Model):
	

class github.com/99designs/gqlgen/graphql/introspection.EnumValue(models.Model):
	

class github.com/99designs/gqlgen/graphql/introspection.Field(models.Model):
	

class github.com/99designs/gqlgen/graphql/introspection.InputValue(models.Model):
	

class github.com/99designs/gqlgen/graphql/introspection.Schema(models.Model):
	

class github.com/99designs/gqlgen/graphql/introspection.Type(models.Model):
	




String

models.CharField(max_length=100)
models.IntegerField()
models.ForeignKey()
    gender = models.CharField(max_length=100, choices=(('M', 'Male'), ('F', 'Female')), default='F')
    movie = models.CharField(max_length=100)

