output   = "generated/db/models"

[psql]
  dbname    = "soap"
  host      = "localhost"
  port      = 15432
  user      = "soap"
  pass      = "soap"
  sslmode   = "disable"
  blacklist = ["auth_group", "auth_group_permissions", "auth_permission", "auth_user", "auth_user_groups", "auth_user_user_permissions", "django_admin_log", "django_content_type", "django_migrations", "django_session"]
